Repository ISG-ICS/Wildfires, pull requests merged in 2019-10, with the labels that each got.

#1 Time Service, Time Series doc
  backend/web/router/data_router.py
  backend/web/router/tweet_router.py
  frontend/src/app/map/layers/fire.tweet.layer.ts
  frontend/src/app/map/time-series/time-series.component.ts
  frontend/src/app/services/time/time.service.ts
Labels: documentation

#2 Add image folder
  README.md
  images/wildfires_readme.jpg
Labels: documentation

#5 Update requirements.txt
  requirements.txt
Labels: fixed

#13 Async tweet load
  backend/web/router/tweet_router.py
  frontend/src/app/map/layers/FireTweetLayer.ts
  frontend/src/app/map/layers/fire.tweet.layer.ts
  frontend/src/app/map/time-series/time-series.component.ts
  frontend/src/app/services/map-service/map.service.ts
  frontend/src/app/services/time/time.service.ts
Labels: feature, fixed
